### ISSUE TITLE
Move release repo moveit_robots to ros-gbp

### ISSUE THREAD

**Issue by 130s** [ros-gbp/moveit-release#4]
Could any admins fork https://github.com/tork-a/moveit_robots-release to `ros-gbp` organization? Since other `moveit*-release` repos are maintained on `ros-gbp` it'd make sense to move `moveit_robots` here as well IMO.

Then I'll update the rosdistro accordingly. Also give a write access to @130s.
Thank you in advance.

**Comment by 130s** [comment]
Can I ask @wjwwood?
 Thank you in advance!

**Comment by wjwwood** [comment]
I can't move it because I don't have admin on the tork-a repo. I can fork it.

**Comment by 130s** [comment]
I hadn't thought of transfer. Now I've transfered to `ros-gbp` and update to rosdistro https://github.com/ros/rosdistro/pull/15012
